[package]
name = "emoji-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
emojis = "0.8.0"
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = "3.1.1"
toml = "0.9.8"
