[package]
name = "updater"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
dirs = "5.0"
notify-rust = "4"
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = "3.1.1"
shlex = "1.3.0"
toml = "0.9.8"

