[package]
name = "cloudflare-toggle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
libc = "0.2"
toml = "0.9.8"
shellexpand = "3.1.1"
serde = { version = "1.0.228", features = ["derive"] }
sysinfo = "0.36.1"
